abbr -a - 'cd -'
abbr -a ... '../..'
abbr -a .... '../../..'
abbr -a ..... '../../../..'
abbr -a ...... '../../../../..'

abbr -a b 'orbit bundle'
abbr -a be 'orbit bundle exec'
abbr -a bi 'orbit bundle install'
abbr -a bp 'orbit pod'
abbr -a bpi 'orbit pod install'
abbr -a cpr 'cp -r'
abbr -a dust1 'dust -d 1'
abbr -a eesc 'orbit eesc'
abbr -a fdd 'fd -td'
abbr -a fdf 'fd -tf'
abbr -a fdu 'fd -u'
abbr -a fzfbat fzf\ --preview\ \'bat\ --style=numbers\ --color=always\ --line-range\ :500\ \{\}\'
abbr -a g git
abbr -a ga 'git add'
abbr -a gaa 'git add --all'
abbr -a gap 'git apply'
abbr -a gb 'git branch'
abbr -a gbd 'git branch -d'
abbr -a gbD 'git branch -D'
abbr -a gbr 'git branch -r'
abbr -a gbv 'git branch -vv'
abbr -a gbl 'git blame --color-by-age'
abbr -a gca 'git commit --amend --no-edit'
abbr -a gcm 'git commit -m'
abbr -a gco 'git checkout'
abbr -a gcp 'git cherry-pick'
abbr -a gd 'git diff'
abbr -a gds 'git diff --staged'
abbr -a gf 'git fetch'
abbr -a gfa 'git fetch --all --prune --prune-tags --jobs=10'
abbr -a gl 'git pull'
abbr -a glg 'git log'
abbr -a glgp 'git log -p'
abbr -a gp 'git push'
abbr -a gpd 'git push --dry-run'
abbr -a gpf 'git push --force-with-lease'
abbr -a gpf! 'git push --force'
abbr -a gpristine 'git reset --hard && git clean -dffx'
abbr -a gr 'git remote'
abbr -a grv 'git remote -v'
abbr -a grb 'git rebase'
abbr -a grse 'git reset'
abbr -a grseup 'git reset --hard (git rev-parse --abbrev-ref --symbolic-full-name @{u})'
abbr -a grs 'git restore'
abbr -a grs/ 'git restore -WS :/'
abbr -a grss 'git restore -S'
abbr -a grss/ 'git restore -S :/'
abbr -a gst 'git status'
abbr -a gsts 'git status -s'
abbr -a gsta 'git stash'
abbr -a gstad 'git stash drop'
abbr -a gstal 'git stash list'
abbr -a gstu 'git stash -u'
abbr -a gsh 'git show'
abbr -a gshs 'git show -s'
abbr -a gsw 'git switch'
abbr -a gswc 'git switch -c'
abbr -a gswf 'git switch -f'
abbr -a gwm 'git when-merged'
abbr -a gup 'git rev-parse --abbrev-ref --symbolic-full-name @{u}'
abbr -a jbat 'prettybat --language=json'
abbr -a lls 'll -s'
abbr -a lrgi 'lrg -i'
abbr -a lrgp 'lrgu -p'
abbr -a lrgu 'lrg -uuu'
abbr -a ob orbit
abbr -a pbat prettybat
abbr -a py python
abbr -a pi 'pod install'
abbr -a ipy ipython
abbr -a rb ruby
abbr -a rgu 'rg -uuu'
abbr -a rmr 'rm -rf'
abbr -a tree 'exa --tree --icons'
abbr -a typep 'type -p'
abbr -a v vim
abbr -a xc 'open -a xcode'
abbr -a xc. 'open -a xcode .'
abbr -a zgr 'cd (git rev-parse --show-toplevel)'
