abbr -a b bundle
abbr -a be 'bundle exec'
abbr -a bi 'bundle install'
abbr -a bp 'bundle exec pod'
abbr -a bpi 'bundle exec pod install'
abbr -a cd- 'cd -'
abbr -a cpr 'cp -r'
abbr -a dust1 'dust -d 1'
abbr -a fdd 'fd -td'
abbr -a fdf 'fd -tf'
abbr -a fdu 'fd -u'
abbr -a fzfbat fzf\ --preview\ \'bat\ --style=numbers\ --color=always\ --line-range\ :500\ \{\}\'
abbr -a g git
abbr -a ga 'git add'
abbr -a gaa 'git add (git rev-parse --show-toplevel)'
abbr -a gb 'git branch'
abbr -a gbd 'git branch -d'
abbr -a gbD 'git branch -D'
abbr -a gbv 'git branch -vv'
abbr -a gbl 'git blame --color-by-age'
abbr -a gcm 'git commit -m'
abbr -a gco 'git checkout'
abbr -a gcp 'git cherry-pick'
abbr -a gd 'git diff'
abbr -a gf 'git fetch'
abbr -a gl 'git log'
abbr -a gpl 'git pull'
abbr -a gps 'git push'
abbr -a gpsf 'git push -f'
abbr -a grb 'git rebase'
abbr -a grse 'git reset'
abbr -a grseup 'git reset --hard (git rev-parse --abbrev-ref --symbolic-full-name @{u})'
abbr -a grs 'git restore'
abbr -a grs/ 'git restore -WS :/'
abbr -a gsta 'git stash'
abbr -a gsts 'git status'
abbr -a gstss 'git status -s'
abbr -a gsw 'git switch'
abbr -a gup 'git rev-parse --abbrev-ref --symbolic-full-name @{u}'
abbr -a jbat 'prettybat --language=json'
abbr -a lls 'll -s'
abbr -a lrgi 'lrg -i'
abbr -a lrgp 'lrgu -p'
abbr -a lrgu 'lrg -uuu'
abbr -a pbat prettybat
abbr -a py python
abbr -a pi 'pod install'
abbr -a ipy ipython
abbr -a rb ruby
abbr -a rgu 'rg -uuu'
abbr -a rmr 'rm -rf'
abbr -a tree 'exa --tree --icons'
abbr -a typep 'type -p'
abbr -a v vim
abbr -a xc 'open -a xcode'
abbr -a xc. 'open -a xcode .'
abbr -a zgr 'cd (git rev-parse --show-toplevel)'
